/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as DemoPrestigeRouteImport } from './routes/demo.prestige'
import { Route as DemoBdloveRouteImport } from './routes/demo.bdlove'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountReturnsRouteImport } from './routes/account.returns'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedThemesRouteImport } from './routes/_authenticated/themes'
import { Route as AuthenticatedThemeBuilderRouteImport } from './routes/_authenticated/theme-builder'
import { Route as AuthenticatedSpotlightsRouteImport } from './routes/_authenticated/spotlights'
import { Route as AuthenticatedSmsSettingsRouteImport } from './routes/_authenticated/sms-settings'
import { Route as AuthenticatedResellerProductsRouteImport } from './routes/_authenticated/reseller-products'
import { Route as AuthenticatedPromoCodesRouteImport } from './routes/_authenticated/promo-codes'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMobileAppRouteImport } from './routes/_authenticated/mobile-app'
import { Route as AuthenticatedManageShopRouteImport } from './routes/_authenticated/manage-shop'
import { Route as AuthenticatedLandingPagesRouteImport } from './routes/_authenticated/landing-pages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCourierRouteImport } from './routes/_authenticated/courier'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as SSlugTeamRouteImport } from './routes/s.$slug.team'
import { Route as SSlugProductsRouteImport } from './routes/s.$slug.products'
import { Route as SSlugPricingRouteImport } from './routes/s.$slug.pricing'
import { Route as SSlugContactRouteImport } from './routes/s.$slug.contact'
import { Route as SSlugBlogsRouteImport } from './routes/s.$slug.blogs'
import { Route as SSlugAboutRouteImport } from './routes/s.$slug.about'
import { Route as ApiPublicResellerSyncRouteImport } from './routes/api/public/reseller-sync'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders_.$id'
import { Route as AuthenticatedCategoriesNewRouteImport } from './routes/_authenticated/categories_.new'
import { Route as SSlugPProductIdRouteImport } from './routes/s.$slug.p.$productId'
import { Route as ApiPublicResellerProductsUser_idRouteImport } from './routes/api/public/reseller-products.$user_id'
import { Route as AuthenticatedProductsProductIdEditRouteImport } from './routes/_authenticated/products.$productId.edit'
import { Route as AuthenticatedCategoriesIdEditRouteImport } from './routes/_authenticated/categories_.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrestigeRoute = DemoPrestigeRouteImport.update({
  id: '/demo/prestige',
  path: '/demo/prestige',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBdloveRoute = DemoBdloveRouteImport.update({
  id: '/demo/bdlove',
  path: '/demo/bdlove',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThemesRoute = AuthenticatedThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThemeBuilderRoute =
  AuthenticatedThemeBuilderRouteImport.update({
    id: '/theme-builder',
    path: '/theme-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpotlightsRoute = AuthenticatedSpotlightsRouteImport.update({
  id: '/spotlights',
  path: '/spotlights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmsSettingsRoute =
  AuthenticatedSmsSettingsRouteImport.update({
    id: '/sms-settings',
    path: '/sms-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerProductsRoute =
  AuthenticatedResellerProductsRouteImport.update({
    id: '/reseller-products',
    path: '/reseller-products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromoCodesRoute = AuthenticatedPromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileAppRoute = AuthenticatedMobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageShopRoute = AuthenticatedManageShopRouteImport.update({
  id: '/manage-shop',
  path: '/manage-shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandingPagesRoute =
  AuthenticatedLandingPagesRouteImport.update({
    id: '/landing-pages',
    path: '/landing-pages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourierRoute = AuthenticatedCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SSlugTeamRoute = SSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugProductsRoute = SSlugProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugPricingRoute = SSlugPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugContactRoute = SSlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugBlogsRoute = SSlugBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugAboutRoute = SSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SSlugRoute,
} as any)
const ApiPublicResellerSyncRoute = ApiPublicResellerSyncRouteImport.update({
  id: '/api/public/reseller-sync',
  path: '/api/public/reseller-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesNewRoute =
  AuthenticatedCategoriesNewRouteImport.update({
    id: '/categories_/new',
    path: '/categories/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SSlugPProductIdRoute = SSlugPProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => SSlugRoute,
} as any)
const ApiPublicResellerProductsUser_idRoute =
  ApiPublicResellerProductsUser_idRouteImport.update({
    id: '/api/public/reseller-products/$user_id',
    path: '/api/public/reseller-products/$user_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsProductIdEditRoute =
  AuthenticatedProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIdEditRoute =
  AuthenticatedCategoriesIdEditRouteImport.update({
    id: '/categories_/$id/edit',
    path: '/categories/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/courier': typeof AuthenticatedCourierRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/landing-pages': typeof AuthenticatedLandingPagesRoute
  '/manage-shop': typeof AuthenticatedManageShopRoute
  '/mobile-app': typeof AuthenticatedMobileAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/promo-codes': typeof AuthenticatedPromoCodesRoute
  '/reseller-products': typeof AuthenticatedResellerProductsRoute
  '/sms-settings': typeof AuthenticatedSmsSettingsRoute
  '/spotlights': typeof AuthenticatedSpotlightsRoute
  '/theme-builder': typeof AuthenticatedThemeBuilderRoute
  '/themes': typeof AuthenticatedThemesRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/demo/bdlove': typeof DemoBdloveRoute
  '/demo/prestige': typeof DemoPrestigeRoute
  '/r/$id': typeof RIdRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/categories/new': typeof AuthenticatedCategoriesNewRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/public/reseller-sync': typeof ApiPublicResellerSyncRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/blogs': typeof SSlugBlogsRoute
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/pricing': typeof SSlugPricingRoute
  '/s/$slug/products': typeof SSlugProductsRoute
  '/s/$slug/team': typeof SSlugTeamRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/categories/$id/edit': typeof AuthenticatedCategoriesIdEditRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/api/public/reseller-products/$user_id': typeof ApiPublicResellerProductsUser_idRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/courier': typeof AuthenticatedCourierRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/landing-pages': typeof AuthenticatedLandingPagesRoute
  '/manage-shop': typeof AuthenticatedManageShopRoute
  '/mobile-app': typeof AuthenticatedMobileAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/promo-codes': typeof AuthenticatedPromoCodesRoute
  '/reseller-products': typeof AuthenticatedResellerProductsRoute
  '/sms-settings': typeof AuthenticatedSmsSettingsRoute
  '/spotlights': typeof AuthenticatedSpotlightsRoute
  '/theme-builder': typeof AuthenticatedThemeBuilderRoute
  '/themes': typeof AuthenticatedThemesRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/demo/bdlove': typeof DemoBdloveRoute
  '/demo/prestige': typeof DemoPrestigeRoute
  '/r/$id': typeof RIdRoute
  '/account': typeof AccountIndexRoute
  '/categories/new': typeof AuthenticatedCategoriesNewRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/public/reseller-sync': typeof ApiPublicResellerSyncRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/blogs': typeof SSlugBlogsRoute
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/pricing': typeof SSlugPricingRoute
  '/s/$slug/products': typeof SSlugProductsRoute
  '/s/$slug/team': typeof SSlugTeamRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/categories/$id/edit': typeof AuthenticatedCategoriesIdEditRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/api/public/reseller-products/$user_id': typeof ApiPublicResellerProductsUser_idRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/courier': typeof AuthenticatedCourierRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/landing-pages': typeof AuthenticatedLandingPagesRoute
  '/_authenticated/manage-shop': typeof AuthenticatedManageShopRoute
  '/_authenticated/mobile-app': typeof AuthenticatedMobileAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/promo-codes': typeof AuthenticatedPromoCodesRoute
  '/_authenticated/reseller-products': typeof AuthenticatedResellerProductsRoute
  '/_authenticated/sms-settings': typeof AuthenticatedSmsSettingsRoute
  '/_authenticated/spotlights': typeof AuthenticatedSpotlightsRoute
  '/_authenticated/theme-builder': typeof AuthenticatedThemeBuilderRoute
  '/_authenticated/themes': typeof AuthenticatedThemesRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/returns': typeof AccountReturnsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/demo/bdlove': typeof DemoBdloveRoute
  '/demo/prestige': typeof DemoPrestigeRoute
  '/r/$id': typeof RIdRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/_authenticated/categories_/new': typeof AuthenticatedCategoriesNewRoute
  '/_authenticated/orders_/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/public/reseller-sync': typeof ApiPublicResellerSyncRoute
  '/s/$slug/about': typeof SSlugAboutRoute
  '/s/$slug/blogs': typeof SSlugBlogsRoute
  '/s/$slug/contact': typeof SSlugContactRoute
  '/s/$slug/pricing': typeof SSlugPricingRoute
  '/s/$slug/products': typeof SSlugProductsRoute
  '/s/$slug/team': typeof SSlugTeamRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/_authenticated/categories_/$id/edit': typeof AuthenticatedCategoriesIdEditRoute
  '/_authenticated/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/api/public/reseller-products/$user_id': typeof ApiPublicResellerProductsUser_idRoute
  '/s/$slug/p/$productId': typeof SSlugPProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/install'
    | '/login'
    | '/offline'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/categories'
    | '/courier'
    | '/customers'
    | '/dashboard'
    | '/landing-pages'
    | '/manage-shop'
    | '/mobile-app'
    | '/onboarding'
    | '/orders'
    | '/promo-codes'
    | '/reseller-products'
    | '/sms-settings'
    | '/spotlights'
    | '/theme-builder'
    | '/themes'
    | '/upgrade'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/wishlist'
    | '/demo/bdlove'
    | '/demo/prestige'
    | '/r/$id'
    | '/s/$slug'
    | '/account/'
    | '/categories/new'
    | '/orders/$id'
    | '/products/new'
    | '/account/orders/$id'
    | '/api/public/reseller-sync'
    | '/s/$slug/about'
    | '/s/$slug/blogs'
    | '/s/$slug/contact'
    | '/s/$slug/pricing'
    | '/s/$slug/products'
    | '/s/$slug/team'
    | '/products/'
    | '/s/$slug/'
    | '/categories/$id/edit'
    | '/products/$productId/edit'
    | '/api/public/reseller-products/$user_id'
    | '/s/$slug/p/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/install'
    | '/login'
    | '/offline'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/categories'
    | '/courier'
    | '/customers'
    | '/dashboard'
    | '/landing-pages'
    | '/manage-shop'
    | '/mobile-app'
    | '/onboarding'
    | '/orders'
    | '/promo-codes'
    | '/reseller-products'
    | '/sms-settings'
    | '/spotlights'
    | '/theme-builder'
    | '/themes'
    | '/upgrade'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/wishlist'
    | '/demo/bdlove'
    | '/demo/prestige'
    | '/r/$id'
    | '/account'
    | '/categories/new'
    | '/orders/$id'
    | '/products/new'
    | '/account/orders/$id'
    | '/api/public/reseller-sync'
    | '/s/$slug/about'
    | '/s/$slug/blogs'
    | '/s/$slug/contact'
    | '/s/$slug/pricing'
    | '/s/$slug/products'
    | '/s/$slug/team'
    | '/products'
    | '/s/$slug'
    | '/categories/$id/edit'
    | '/products/$productId/edit'
    | '/api/public/reseller-products/$user_id'
    | '/s/$slug/p/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/auth'
    | '/install'
    | '/login'
    | '/offline'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/categories'
    | '/_authenticated/courier'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/landing-pages'
    | '/_authenticated/manage-shop'
    | '/_authenticated/mobile-app'
    | '/_authenticated/onboarding'
    | '/_authenticated/orders'
    | '/_authenticated/promo-codes'
    | '/_authenticated/reseller-products'
    | '/_authenticated/sms-settings'
    | '/_authenticated/spotlights'
    | '/_authenticated/theme-builder'
    | '/_authenticated/themes'
    | '/_authenticated/upgrade'
    | '/account/orders'
    | '/account/returns'
    | '/account/reviews'
    | '/account/wishlist'
    | '/demo/bdlove'
    | '/demo/prestige'
    | '/r/$id'
    | '/s/$slug'
    | '/account/'
    | '/_authenticated/categories_/new'
    | '/_authenticated/orders_/$id'
    | '/_authenticated/products/new'
    | '/account/orders/$id'
    | '/api/public/reseller-sync'
    | '/s/$slug/about'
    | '/s/$slug/blogs'
    | '/s/$slug/contact'
    | '/s/$slug/pricing'
    | '/s/$slug/products'
    | '/s/$slug/team'
    | '/_authenticated/products/'
    | '/s/$slug/'
    | '/_authenticated/categories_/$id/edit'
    | '/_authenticated/products/$productId/edit'
    | '/api/public/reseller-products/$user_id'
    | '/s/$slug/p/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DemoBdloveRoute: typeof DemoBdloveRoute
  DemoPrestigeRoute: typeof DemoPrestigeRoute
  RIdRoute: typeof RIdRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  ApiPublicResellerSyncRoute: typeof ApiPublicResellerSyncRoute
  ApiPublicResellerProductsUser_idRoute: typeof ApiPublicResellerProductsUser_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prestige': {
      id: '/demo/prestige'
      path: '/demo/prestige'
      fullPath: '/demo/prestige'
      preLoaderRoute: typeof DemoPrestigeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/bdlove': {
      id: '/demo/bdlove'
      path: '/demo/bdlove'
      fullPath: '/demo/bdlove'
      preLoaderRoute: typeof DemoBdloveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/returns': {
      id: '/account/returns'
      path: '/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/themes': {
      id: '/_authenticated/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof AuthenticatedThemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theme-builder': {
      id: '/_authenticated/theme-builder'
      path: '/theme-builder'
      fullPath: '/theme-builder'
      preLoaderRoute: typeof AuthenticatedThemeBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spotlights': {
      id: '/_authenticated/spotlights'
      path: '/spotlights'
      fullPath: '/spotlights'
      preLoaderRoute: typeof AuthenticatedSpotlightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms-settings': {
      id: '/_authenticated/sms-settings'
      path: '/sms-settings'
      fullPath: '/sms-settings'
      preLoaderRoute: typeof AuthenticatedSmsSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-products': {
      id: '/_authenticated/reseller-products'
      path: '/reseller-products'
      fullPath: '/reseller-products'
      preLoaderRoute: typeof AuthenticatedResellerProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo-codes': {
      id: '/_authenticated/promo-codes'
      path: '/promo-codes'
      fullPath: '/promo-codes'
      preLoaderRoute: typeof AuthenticatedPromoCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-app': {
      id: '/_authenticated/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof AuthenticatedMobileAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-shop': {
      id: '/_authenticated/manage-shop'
      path: '/manage-shop'
      fullPath: '/manage-shop'
      preLoaderRoute: typeof AuthenticatedManageShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing-pages': {
      id: '/_authenticated/landing-pages'
      path: '/landing-pages'
      fullPath: '/landing-pages'
      preLoaderRoute: typeof AuthenticatedLandingPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courier': {
      id: '/_authenticated/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof AuthenticatedCourierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/team': {
      id: '/s/$slug/team'
      path: '/team'
      fullPath: '/s/$slug/team'
      preLoaderRoute: typeof SSlugTeamRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/products': {
      id: '/s/$slug/products'
      path: '/products'
      fullPath: '/s/$slug/products'
      preLoaderRoute: typeof SSlugProductsRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/pricing': {
      id: '/s/$slug/pricing'
      path: '/pricing'
      fullPath: '/s/$slug/pricing'
      preLoaderRoute: typeof SSlugPricingRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/contact': {
      id: '/s/$slug/contact'
      path: '/contact'
      fullPath: '/s/$slug/contact'
      preLoaderRoute: typeof SSlugContactRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/blogs': {
      id: '/s/$slug/blogs'
      path: '/blogs'
      fullPath: '/s/$slug/blogs'
      preLoaderRoute: typeof SSlugBlogsRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/about': {
      id: '/s/$slug/about'
      path: '/about'
      fullPath: '/s/$slug/about'
      preLoaderRoute: typeof SSlugAboutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/api/public/reseller-sync': {
      id: '/api/public/reseller-sync'
      path: '/api/public/reseller-sync'
      fullPath: '/api/public/reseller-sync'
      preLoaderRoute: typeof ApiPublicResellerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders_/$id': {
      id: '/_authenticated/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories_/new': {
      id: '/_authenticated/categories_/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof AuthenticatedCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/p/$productId': {
      id: '/s/$slug/p/$productId'
      path: '/p/$productId'
      fullPath: '/s/$slug/p/$productId'
      preLoaderRoute: typeof SSlugPProductIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/api/public/reseller-products/$user_id': {
      id: '/api/public/reseller-products/$user_id'
      path: '/api/public/reseller-products/$user_id'
      fullPath: '/api/public/reseller-products/$user_id'
      preLoaderRoute: typeof ApiPublicResellerProductsUser_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/$productId/edit': {
      id: '/_authenticated/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories_/$id/edit': {
      id: '/_authenticated/categories_/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/categories/$id/edit'
      preLoaderRoute: typeof AuthenticatedCategoriesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCourierRoute: typeof AuthenticatedCourierRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLandingPagesRoute: typeof AuthenticatedLandingPagesRoute
  AuthenticatedManageShopRoute: typeof AuthenticatedManageShopRoute
  AuthenticatedMobileAppRoute: typeof AuthenticatedMobileAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPromoCodesRoute: typeof AuthenticatedPromoCodesRoute
  AuthenticatedResellerProductsRoute: typeof AuthenticatedResellerProductsRoute
  AuthenticatedSmsSettingsRoute: typeof AuthenticatedSmsSettingsRoute
  AuthenticatedSpotlightsRoute: typeof AuthenticatedSpotlightsRoute
  AuthenticatedThemeBuilderRoute: typeof AuthenticatedThemeBuilderRoute
  AuthenticatedThemesRoute: typeof AuthenticatedThemesRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedCategoriesNewRoute: typeof AuthenticatedCategoriesNewRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedCategoriesIdEditRoute: typeof AuthenticatedCategoriesIdEditRoute
  AuthenticatedProductsProductIdEditRoute: typeof AuthenticatedProductsProductIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCourierRoute: AuthenticatedCourierRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLandingPagesRoute: AuthenticatedLandingPagesRoute,
  AuthenticatedManageShopRoute: AuthenticatedManageShopRoute,
  AuthenticatedMobileAppRoute: AuthenticatedMobileAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPromoCodesRoute: AuthenticatedPromoCodesRoute,
  AuthenticatedResellerProductsRoute: AuthenticatedResellerProductsRoute,
  AuthenticatedSmsSettingsRoute: AuthenticatedSmsSettingsRoute,
  AuthenticatedSpotlightsRoute: AuthenticatedSpotlightsRoute,
  AuthenticatedThemeBuilderRoute: AuthenticatedThemeBuilderRoute,
  AuthenticatedThemesRoute: AuthenticatedThemesRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedCategoriesNewRoute: AuthenticatedCategoriesNewRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedCategoriesIdEditRoute: AuthenticatedCategoriesIdEditRoute,
  AuthenticatedProductsProductIdEditRoute:
    AuthenticatedProductsProductIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface SSlugRouteChildren {
  SSlugAboutRoute: typeof SSlugAboutRoute
  SSlugBlogsRoute: typeof SSlugBlogsRoute
  SSlugContactRoute: typeof SSlugContactRoute
  SSlugPricingRoute: typeof SSlugPricingRoute
  SSlugProductsRoute: typeof SSlugProductsRoute
  SSlugTeamRoute: typeof SSlugTeamRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugPProductIdRoute: typeof SSlugPProductIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugAboutRoute: SSlugAboutRoute,
  SSlugBlogsRoute: SSlugBlogsRoute,
  SSlugContactRoute: SSlugContactRoute,
  SSlugPricingRoute: SSlugPricingRoute,
  SSlugProductsRoute: SSlugProductsRoute,
  SSlugTeamRoute: SSlugTeamRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugPProductIdRoute: SSlugPProductIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DemoBdloveRoute: DemoBdloveRoute,
  DemoPrestigeRoute: DemoPrestigeRoute,
  RIdRoute: RIdRoute,
  SSlugRoute: SSlugRouteWithChildren,
  ApiPublicResellerSyncRoute: ApiPublicResellerSyncRoute,
  ApiPublicResellerProductsUser_idRoute: ApiPublicResellerProductsUser_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
